[package]
name = "comboman"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
chrono = { version = "0.4", features = ["serde"] }
ratatui = "0.20"
crossterm = "0.26"
fuzzy-matcher = "0.3"
shellexpand = "2.1"
tempfile = "3.3"
